name: MaManga Android CI
on:
  pull_request:
    branches: [ main, development ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 1.8
      # Execute unit tests
      - name: Unit Test
        run: ./gradlew testDebugUnitTest
      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
      # Upload Debug APK  
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          name: MaManga
          path: app/build/outputs/apk/debug
          
